-- Central decision store.
--
-- One Big Table: every row is a single decision extracted from a
-- <decision_log> block left in an agent session by the skill.
--
-- `id` is "<provider>:<message id>", taken straight from the session .jsonl
-- file. Message ids are only unique within one tool, hence the prefix. It is NOT generated here and NOT generated by the extractor.
-- That matters: sessions are append-only files that get re-read in full on
-- every extractor run, so the key has to be stable across runs and unique
-- per decision. A session-level key (sessionId, or sessionId+developer)
-- silently drops every decision but the first via ON CONFLICT DO NOTHING;
-- a freshly generated uuid() duplicates every decision on every run.
--
-- `embedding` is a fixed-size FLOAT array, so array_cosine_similarity()
-- works without the VSS extension. The dimension must match whatever model
-- fills it -- it mirrors EMBEDDING_DIM in common/embeddings.py. Changing the
-- model means changing this number and re-computing every vector, so pick
-- the model first.
--
-- NULL embedding doubles as the work queue for the embedding worker; see
-- worker_embeddings.py. No task table needed: a row states its own status.

CREATE TABLE IF NOT EXISTS decisions (
    id               VARCHAR PRIMARY KEY,   -- uuid of the source message
    created_at       TIMESTAMP DEFAULT current_timestamp,
    developer_id     VARCHAR,
    provider         VARCHAR,               -- claude | gemini | codex
    seniority_level  VARCHAR,               -- junior | mid | senior
    project          VARCHAR,
    session_uuid     VARCHAR,               -- pointer only; the session file never leaves the laptop
    decision_type    VARCHAR,               -- decision | assumption | solution
    -- The three parts every marker must carry. A decision without its
    -- assumptions cannot be judged as applicable by the next person, and one
    -- without its rationale is just an outcome -- which the code already shows.
    decision_summary VARCHAR NOT NULL,      -- 1. what was decided
    assumptions_tech VARCHAR[],             -- 2a. technical assumptions
    assumptions_biz  VARCHAR[],             -- 2b. business assumptions
    rationale        VARCHAR,               -- 3. why this one was chosen
    rejected_options VARCHAR[],             -- 3b. and why the others were not
    tags             VARCHAR[],             -- closed vocabulary, see TAGS in tags.py
    status           VARCHAR DEFAULT 'unknown',  -- unknown | confirmed | rejected
    embedding        FLOAT[16]
);

-- No index on `embedding`, deliberately. Retrieval uses
-- array_cosine_similarity(), which is a core DuckDB function -- verified
-- working with no extension loaded at all. At a few dozen rows a full scan
-- beats maintaining an ANN index, and rows still waiting for the embedding
-- worker score 0 instead of being invisible.
--
-- If the corpus ever outgrows that, vss adds an HNSW index -- but it must be
-- loaded by the server process at startup, and on a persistent database it
-- needs hnsw_enable_experimental_persistence, which carries a data-loss
-- warning. Treat any such index as a rebuildable cache:
--
--   INSTALL vss; LOAD vss;
--   SET hnsw_enable_experimental_persistence = true;
--   CREATE INDEX decisions_embedding_idx ON decisions
--   USING HNSW (embedding) WITH (metric = 'cosine');
